/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    organizations: Organization
    'organization-memberships': OrganizationMembership
    'organization-invitations': OrganizationInvitation
    'organization-settings': OrganizationSetting
    'google-connections': GoogleConnection
    'google-connection-scopes': GoogleConnectionScope
    'play-console-profiles': PlayConsoleProfile
    'google-ads-accounts': GoogleAdsAccount
    'admob-accounts': AdmobAccount
    apps: App
    'google-ads-campaigns': GoogleAdsCampaign
    'admob-apps': AdmobApp
    'admob-ad-units': AdmobAdUnit
    'campaign-app-mappings': CampaignAppMapping
    'admob-app-mappings': AdmobAppMapping
    'google-ads-daily-stats': GoogleAdsDailyStat
    'admob-daily-stats': AdmobDailyStat
    'play-daily-stats': PlayDailyStat
    'play-financial-transactions': PlayFinancialTransaction
    'play-financial-daily-aggregates': PlayFinancialDailyAggregate
    'app-daily-financials': AppDailyFinancial
    'account-daily-financials': AccountDailyFinancial
    'organization-daily-financials': OrganizationDailyFinancial
    'manual-expenses': ManualExpense
    'expense-categories': ExpenseCategory
    'expense-allocations': ExpenseAllocation
    'currency-rates': CurrencyRate
    'sync-runs': SyncRun
    'sync-tasks': SyncTask
    'sync-cursors': SyncCursor
    'source-files': SourceFile
    'integration-errors': IntegrationError
    notifications: Notification
    'saved-reports': SavedReport
    'report-exports': ReportExport
    'audit-logs': AuditLog
    media: Media
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {
    users: {
      memberships: 'organization-memberships'
    }
  }
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>
    'organization-memberships':
      | OrganizationMembershipsSelect<false>
      | OrganizationMembershipsSelect<true>
    'organization-invitations':
      | OrganizationInvitationsSelect<false>
      | OrganizationInvitationsSelect<true>
    'organization-settings':
      | OrganizationSettingsSelect<false>
      | OrganizationSettingsSelect<true>
    'google-connections': GoogleConnectionsSelect<false> | GoogleConnectionsSelect<true>
    'google-connection-scopes':
      | GoogleConnectionScopesSelect<false>
      | GoogleConnectionScopesSelect<true>
    'play-console-profiles':
      | PlayConsoleProfilesSelect<false>
      | PlayConsoleProfilesSelect<true>
    'google-ads-accounts': GoogleAdsAccountsSelect<false> | GoogleAdsAccountsSelect<true>
    'admob-accounts': AdmobAccountsSelect<false> | AdmobAccountsSelect<true>
    apps: AppsSelect<false> | AppsSelect<true>
    'google-ads-campaigns':
      | GoogleAdsCampaignsSelect<false>
      | GoogleAdsCampaignsSelect<true>
    'admob-apps': AdmobAppsSelect<false> | AdmobAppsSelect<true>
    'admob-ad-units': AdmobAdUnitsSelect<false> | AdmobAdUnitsSelect<true>
    'campaign-app-mappings':
      | CampaignAppMappingsSelect<false>
      | CampaignAppMappingsSelect<true>
    'admob-app-mappings': AdmobAppMappingsSelect<false> | AdmobAppMappingsSelect<true>
    'google-ads-daily-stats':
      | GoogleAdsDailyStatsSelect<false>
      | GoogleAdsDailyStatsSelect<true>
    'admob-daily-stats': AdmobDailyStatsSelect<false> | AdmobDailyStatsSelect<true>
    'play-daily-stats': PlayDailyStatsSelect<false> | PlayDailyStatsSelect<true>
    'play-financial-transactions':
      | PlayFinancialTransactionsSelect<false>
      | PlayFinancialTransactionsSelect<true>
    'play-financial-daily-aggregates':
      | PlayFinancialDailyAggregatesSelect<false>
      | PlayFinancialDailyAggregatesSelect<true>
    'app-daily-financials':
      | AppDailyFinancialsSelect<false>
      | AppDailyFinancialsSelect<true>
    'account-daily-financials':
      | AccountDailyFinancialsSelect<false>
      | AccountDailyFinancialsSelect<true>
    'organization-daily-financials':
      | OrganizationDailyFinancialsSelect<false>
      | OrganizationDailyFinancialsSelect<true>
    'manual-expenses': ManualExpensesSelect<false> | ManualExpensesSelect<true>
    'expense-categories': ExpenseCategoriesSelect<false> | ExpenseCategoriesSelect<true>
    'expense-allocations':
      | ExpenseAllocationsSelect<false>
      | ExpenseAllocationsSelect<true>
    'currency-rates': CurrencyRatesSelect<false> | CurrencyRatesSelect<true>
    'sync-runs': SyncRunsSelect<false> | SyncRunsSelect<true>
    'sync-tasks': SyncTasksSelect<false> | SyncTasksSelect<true>
    'sync-cursors': SyncCursorsSelect<false> | SyncCursorsSelect<true>
    'source-files': SourceFilesSelect<false> | SourceFilesSelect<true>
    'integration-errors': IntegrationErrorsSelect<false> | IntegrationErrorsSelect<true>
    notifications: NotificationsSelect<false> | NotificationsSelect<true>
    'saved-reports': SavedReportsSelect<false> | SavedReportsSelect<true>
    'report-exports': ReportExportsSelect<false> | ReportExportsSelect<true>
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences':
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  fallbackLocale: null
  globals: {}
  globalsSelect: {}
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string
  name: string
  platformRole: 'user' | 'platform-support' | 'platform-admin'
  activeOrganization?: (string | null) | Organization
  memberships?: {
    docs?: (string | OrganizationMembership)[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  _verified?: boolean | null
  _verificationToken?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string
  name: string
  slug: string
  baseCurrency: string
  timezone: string
  fiscalYearStart?: number | null
  reportingDayCutoff?: number | null
  archivedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships".
 */
export interface OrganizationMembership {
  id: string
  organization: string | Organization
  user: string | User
  role: 'owner' | 'admin' | 'finance' | 'analyst' | 'developer' | 'viewer'
  status: 'invited' | 'active' | 'suspended'
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-invitations".
 */
export interface OrganizationInvitation {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  email: string
  role?: ('owner' | 'admin' | 'finance' | 'analyst' | 'developer' | 'viewer') | null
  tokenHash: string
  expiresAt: string
  acceptedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-settings".
 */
export interface OrganizationSetting {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  breakEvenTolerance?: number | null
  includePreliminaryAdmob?: boolean | null
  developerFinancialAccess?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connections".
 */
export interface GoogleConnection {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  googleEmail: string
  encryptedRefreshToken?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  tokenKeyVersion?: string | null
  lastHealthCheck?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connection-scopes".
 */
export interface GoogleConnectionScope {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  connection: string | GoogleConnection
  scope: string
  grantedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-console-profiles".
 */
export interface PlayConsoleProfile {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  connection: string | GoogleConnection
  developerAccountId?: string | null
  bucketId?: string | null
  timezone?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-ads-accounts".
 */
export interface GoogleAdsAccount {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  connection: string | GoogleConnection
  externalCustomerId: string
  managerCustomerId?: string | null
  timezone?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-accounts".
 */
export interface AdmobAccount {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  connection: string | GoogleConnection
  publisherId: string
  timezone?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps".
 */
export interface App {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  packageName: string
  displayPackageName?: string | null
  playProfile?: (string | null) | PlayConsoleProfile
  iconUrl?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-ads-campaigns".
 */
export interface GoogleAdsCampaign {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  sourceAccount: string | GoogleAdsAccount
  externalCampaignId: string
  appId?: string | null
  channelType?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-apps".
 */
export interface AdmobApp {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  sourceAccount: string | AdmobAccount
  packageName?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-ad-units".
 */
export interface AdmobAdUnit {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  admobApp: string | AdmobApp
  format?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-app-mappings".
 */
export interface CampaignAppMapping {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  campaign: string | GoogleAdsCampaign
  app: string | App
  mappingMethod: 'exact-id' | 'confirmed-auto' | 'manual' | 'fuzzy-suggestion'
  confidence?: number | null
  confirmedBy?: (string | null) | User
  confirmedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-app-mappings".
 */
export interface AdmobAppMapping {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  admobApp: string | AdmobApp
  app: string | App
  mappingMethod?: ('exact-id' | 'confirmed-auto' | 'manual' | 'fuzzy-suggestion') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-ads-daily-stats".
 */
export interface GoogleAdsDailyStat {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-daily-stats".
 */
export interface AdmobDailyStat {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-daily-stats".
 */
export interface PlayDailyStat {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-financial-transactions".
 */
export interface PlayFinancialTransaction {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-financial-daily-aggregates".
 */
export interface PlayFinancialDailyAggregate {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-daily-financials".
 */
export interface AppDailyFinancial {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-daily-financials".
 */
export interface AccountDailyFinancial {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-daily-financials".
 */
export interface OrganizationDailyFinancial {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  app?: (string | null) | App
  sourceAccountId?: string | null
  sourceKey?: string | null
  micros?: number | null
  calculationVersion?: string | null
  finalized?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual-expenses".
 */
export interface ManualExpense {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  vendor?: string | null
  description: string
  category: string | ExpenseCategory
  app?: (string | null) | App
  taxAmount?: number | null
  recurring?: boolean | null
  allocationMethod?:
    | (
        | 'direct'
        | 'fixed-percentage'
        | 'revenue'
        | 'ad-spend'
        | 'equal'
        | 'organization-only'
      )
    | null
  receipt?: (string | null) | Media
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories".
 */
export interface ExpenseCategory {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  pathname: string
  contentType: string
  size: number
  checksum: string
  originalFilename: string
  category: string
  uploader?: (string | null) | User
  retentionUntil?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-allocations".
 */
export interface ExpenseAllocation {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  expense: string | ManualExpense
  app: string | App
  percentage?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currency-rates".
 */
export interface CurrencyRate {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  quoteCurrency?: string | null
  rate?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-runs".
 */
export interface SyncRun {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-tasks".
 */
export interface SyncTask {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-cursors".
 */
export interface SyncCursor {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-files".
 */
export interface SourceFile {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-errors".
 */
export interface IntegrationError {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-reports".
 */
export interface SavedReport {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-exports".
 */
export interface ReportExport {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string
  organization: string | Organization
  name?: string | null
  externalId?: string | null
  date?: string | null
  amount?: number | null
  currency?: string | null
  status?:
    | (
        | 'active'
        | 'inactive'
        | 'pending'
        | 'queued'
        | 'running'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'dead-letter'
        | 'preliminary'
        | 'finalized'
        | 'archived'
      )
    | null
  sourceMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  archivedAt?: string | null
  correlationId?: string | null
  idempotencyKey?: string | null
  attempts?: number | null
  nextAttemptAt?: string | null
  lastError?: string | null
  payload?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string
  document?:
    | ({
        relationTo: 'users'
        value: string | User
      } | null)
    | ({
        relationTo: 'organizations'
        value: string | Organization
      } | null)
    | ({
        relationTo: 'organization-memberships'
        value: string | OrganizationMembership
      } | null)
    | ({
        relationTo: 'organization-invitations'
        value: string | OrganizationInvitation
      } | null)
    | ({
        relationTo: 'organization-settings'
        value: string | OrganizationSetting
      } | null)
    | ({
        relationTo: 'google-connections'
        value: string | GoogleConnection
      } | null)
    | ({
        relationTo: 'google-connection-scopes'
        value: string | GoogleConnectionScope
      } | null)
    | ({
        relationTo: 'play-console-profiles'
        value: string | PlayConsoleProfile
      } | null)
    | ({
        relationTo: 'google-ads-accounts'
        value: string | GoogleAdsAccount
      } | null)
    | ({
        relationTo: 'admob-accounts'
        value: string | AdmobAccount
      } | null)
    | ({
        relationTo: 'apps'
        value: string | App
      } | null)
    | ({
        relationTo: 'google-ads-campaigns'
        value: string | GoogleAdsCampaign
      } | null)
    | ({
        relationTo: 'admob-apps'
        value: string | AdmobApp
      } | null)
    | ({
        relationTo: 'admob-ad-units'
        value: string | AdmobAdUnit
      } | null)
    | ({
        relationTo: 'campaign-app-mappings'
        value: string | CampaignAppMapping
      } | null)
    | ({
        relationTo: 'admob-app-mappings'
        value: string | AdmobAppMapping
      } | null)
    | ({
        relationTo: 'google-ads-daily-stats'
        value: string | GoogleAdsDailyStat
      } | null)
    | ({
        relationTo: 'admob-daily-stats'
        value: string | AdmobDailyStat
      } | null)
    | ({
        relationTo: 'play-daily-stats'
        value: string | PlayDailyStat
      } | null)
    | ({
        relationTo: 'play-financial-transactions'
        value: string | PlayFinancialTransaction
      } | null)
    | ({
        relationTo: 'play-financial-daily-aggregates'
        value: string | PlayFinancialDailyAggregate
      } | null)
    | ({
        relationTo: 'app-daily-financials'
        value: string | AppDailyFinancial
      } | null)
    | ({
        relationTo: 'account-daily-financials'
        value: string | AccountDailyFinancial
      } | null)
    | ({
        relationTo: 'organization-daily-financials'
        value: string | OrganizationDailyFinancial
      } | null)
    | ({
        relationTo: 'manual-expenses'
        value: string | ManualExpense
      } | null)
    | ({
        relationTo: 'expense-categories'
        value: string | ExpenseCategory
      } | null)
    | ({
        relationTo: 'expense-allocations'
        value: string | ExpenseAllocation
      } | null)
    | ({
        relationTo: 'currency-rates'
        value: string | CurrencyRate
      } | null)
    | ({
        relationTo: 'sync-runs'
        value: string | SyncRun
      } | null)
    | ({
        relationTo: 'sync-tasks'
        value: string | SyncTask
      } | null)
    | ({
        relationTo: 'sync-cursors'
        value: string | SyncCursor
      } | null)
    | ({
        relationTo: 'source-files'
        value: string | SourceFile
      } | null)
    | ({
        relationTo: 'integration-errors'
        value: string | IntegrationError
      } | null)
    | ({
        relationTo: 'notifications'
        value: string | Notification
      } | null)
    | ({
        relationTo: 'saved-reports'
        value: string | SavedReport
      } | null)
    | ({
        relationTo: 'report-exports'
        value: string | ReportExport
      } | null)
    | ({
        relationTo: 'audit-logs'
        value: string | AuditLog
      } | null)
    | ({
        relationTo: 'media'
        value: string | Media
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: string | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  platformRole?: T
  activeOrganization?: T
  memberships?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  _verified?: T
  _verificationToken?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  baseCurrency?: T
  timezone?: T
  fiscalYearStart?: T
  reportingDayCutoff?: T
  archivedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships_select".
 */
export interface OrganizationMembershipsSelect<T extends boolean = true> {
  organization?: T
  user?: T
  role?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-invitations_select".
 */
export interface OrganizationInvitationsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  email?: T
  role?: T
  tokenHash?: T
  expiresAt?: T
  acceptedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-settings_select".
 */
export interface OrganizationSettingsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  breakEvenTolerance?: T
  includePreliminaryAdmob?: T
  developerFinancialAccess?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connections_select".
 */
export interface GoogleConnectionsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  googleEmail?: T
  encryptedRefreshToken?: T
  tokenKeyVersion?: T
  lastHealthCheck?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connection-scopes_select".
 */
export interface GoogleConnectionScopesSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  connection?: T
  scope?: T
  grantedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-console-profiles_select".
 */
export interface PlayConsoleProfilesSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  connection?: T
  developerAccountId?: T
  bucketId?: T
  timezone?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-ads-accounts_select".
 */
export interface GoogleAdsAccountsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  connection?: T
  externalCustomerId?: T
  managerCustomerId?: T
  timezone?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-accounts_select".
 */
export interface AdmobAccountsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  connection?: T
  publisherId?: T
  timezone?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps_select".
 */
export interface AppsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  packageName?: T
  displayPackageName?: T
  playProfile?: T
  iconUrl?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-ads-campaigns_select".
 */
export interface GoogleAdsCampaignsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  sourceAccount?: T
  externalCampaignId?: T
  appId?: T
  channelType?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-apps_select".
 */
export interface AdmobAppsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  sourceAccount?: T
  packageName?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-ad-units_select".
 */
export interface AdmobAdUnitsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  admobApp?: T
  format?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-app-mappings_select".
 */
export interface CampaignAppMappingsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  campaign?: T
  app?: T
  mappingMethod?: T
  confidence?: T
  confirmedBy?: T
  confirmedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-app-mappings_select".
 */
export interface AdmobAppMappingsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  admobApp?: T
  app?: T
  mappingMethod?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-ads-daily-stats_select".
 */
export interface GoogleAdsDailyStatsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admob-daily-stats_select".
 */
export interface AdmobDailyStatsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-daily-stats_select".
 */
export interface PlayDailyStatsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-financial-transactions_select".
 */
export interface PlayFinancialTransactionsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "play-financial-daily-aggregates_select".
 */
export interface PlayFinancialDailyAggregatesSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-daily-financials_select".
 */
export interface AppDailyFinancialsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-daily-financials_select".
 */
export interface AccountDailyFinancialsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-daily-financials_select".
 */
export interface OrganizationDailyFinancialsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  app?: T
  sourceAccountId?: T
  sourceKey?: T
  micros?: T
  calculationVersion?: T
  finalized?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual-expenses_select".
 */
export interface ManualExpensesSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  vendor?: T
  description?: T
  category?: T
  app?: T
  taxAmount?: T
  recurring?: T
  allocationMethod?: T
  receipt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories_select".
 */
export interface ExpenseCategoriesSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-allocations_select".
 */
export interface ExpenseAllocationsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  expense?: T
  app?: T
  percentage?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currency-rates_select".
 */
export interface CurrencyRatesSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  quoteCurrency?: T
  rate?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-runs_select".
 */
export interface SyncRunsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-tasks_select".
 */
export interface SyncTasksSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-cursors_select".
 */
export interface SyncCursorsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-files_select".
 */
export interface SourceFilesSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-errors_select".
 */
export interface IntegrationErrorsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-reports_select".
 */
export interface SavedReportsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-exports_select".
 */
export interface ReportExportsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  correlationId?: T
  idempotencyKey?: T
  attempts?: T
  nextAttemptAt?: T
  lastError?: T
  payload?: T
  expiresAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  organization?: T
  name?: T
  externalId?: T
  date?: T
  amount?: T
  currency?: T
  status?: T
  sourceMetadata?: T
  archivedAt?: T
  pathname?: T
  contentType?: T
  size?: T
  checksum?: T
  originalFilename?: T
  category?: T
  uploader?: T
  retentionUntil?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
